"""Add JSONB field and pg_trgm+GIN index to subjectsC

Revision ID: b7416a68c257
Revises: 
Create Date: 2023-11-30 11:27:58.403408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7416a68c257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_subject_data_trgm_gin', 'subject', ['data'], unique=False, postgresql_using='gin',
                    postgresql_ops={'data': 'jsonb_path_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subject_data_trgm_gin', table_name='subject', postgresql_using='gin',
                  postgresql_ops={'data': 'gin_trgm_ops'})
    op.drop_column('subject', 'data')
    # ### end Alembic commands ###
